---
title: "Stat 245 -- Tidy Dataset"
author: "James Eapen, Myungha Kim, Ivanna Rodriguez"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: 
  pdf_document:
    fig_height: 2.2
    fig_width: 4
  html_document:
    fig_height: 2.2
    fig_width: 4
  word_document:
    fig_height: 2.2
    fig_width: 4
---

```{r, setup, include = FALSE}
# load packages that are going to be used
require(tidyverse)   # this loads mosaic, ggformula, etc. too
require(ggformula)
require(mosaic)

# Some customization.  You can alter or delete as desired (if you know what you are doing).

theme_set(theme_bw(base_size=12))     # change theme for ggplot2/ggformula

knitr::opts_chunk$set(
  echo = TRUE,      # for homework, always show R code (this is the default)
  tidy = FALSE,     # display code as typed (rather than reformatted)
  size = "small",   # slightly smaller font for code
  message = FALSE, warning = FALSE) # don't print warnings or messages in compiled document. So you MUST check them in RStudio!
```

## Read dataset
```{r}
bihs_household <- readxl::read_excel('BIHS_household_2011_15.xlsx')
```
## Set year as a categorical variable
```{r}
bihs_household <- bihs_household %>% mutate(survey_year = factor(survey_year))
```

## Rename variables
```{r}
bihs_household <- bihs_household %>% rename(year = survey_year, 
                                            id = a01,
                                            mean_annual_temp = bio_bio_1 ,
                                            annual_precip = bio_bio_12,
                                            gender_parity_gap = weai_parity_gap)
```

## Select variables of interest
```{r}
final_bihs <- bihs_household %>% select(id,
                                        year,
                                        hhhead_gender,
                                        hhhead_education,
                                        hhhead_literate,
                                        memb_total,
                                        memb_und15,
                                        memb_15_44,
                                        gender_parity_gap,
                                        asset_cartplough, 
                                        asset_motorbike,
                                        asset_qty_poultry,
                                        asset_qty_cattle,
                                        asset_qty_otherlivestock,
                                        asset_qty_sheepgoat,
                                        asset_television,
                                        asset_radio,
                                        asset_telephone,
                                        asset_tractor,
                                        asset_television,
                                        fcs,
                                        hhs_total,
                                        mean_annual_temp,
                                        annual_precip)
write.csv(final_bihs, "bihs_final.csv")
```

```{r}
glimpse(final_bihs)
```

Plots
```{r}
gf_boxplot(fcs ~ year, data = final_bihs, ylab = "Food Consumption score", xlab = "Year") 

gf_point(fcs ~ gender_parity_gap, data = final_bihs, xlab = "Gender Parity Gap", ylab = "Food Consumption Score")
gf_boxplot(fcs ~ factor(hhs_total), data = final_bihs, xlab = "Household Hunger Total", ylab = "Food Consumption Score")
gf_bar(~hhhead_gender, data = subset(final_bihs, !is.na(asset_telephone)), xlab = "Gender", ylab = "Count", fill = ~ asset_telephone, factor(year))

```


