---
title: "Income Model"
author: "A. Student"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: 
  html_document:
    fig_height: 2.2
    fig_width: 4
  pdf_document:
    fig_height: 2.2
    fig_width: 4
  word_document:
    fig_height: 2.2
    fig_width: 4
---

```{r, setup, include = FALSE}
# load packages that are going to be used
require(tidyverse)   # this loads mosaic, ggformula, etc. too
require(ggformula)
require(mosaic)

# to read excel files
require(readxl)
# for collinearity
require(GGally)
# for IC
require(MuMIn)
# for VIF
require(car)


# Some customization.  You can alter or delete as desired (if you know what you are doing).

theme_set(theme_bw(base_size=12))     # change theme for ggplot2/ggformula

knitr::opts_chunk$set(
  echo = TRUE,      # for homework, always show R code (this is the default)
  tidy = FALSE,     # display code as typed (rather than reformatted)
  size = "small",   # slightly smaller font for code
  message = FALSE, warning = FALSE) # don't print warnings or messages in compiled document. So you MUST check them in RStudio!
```


```{r, include = FALSE}
# reading in the data
bihs <- read_csv('bihs_final.csv')
bihs_original <- read_excel('../tidy_dataset/BIHS_household_2011_15.xlsx')
```

```{r, include = FALSE}
# data prep
bihs <- bihs%>%mutate(house_owned = bihs_original$house_owned)
bihs_original$survey_year <- as.factor(bihs_original$survey_year)
```

```{r}
# selecting data
bihs_original <- bihs_original%>% 
  select(
          fcs,
          survey_year,
          asset_qty_poultry,
          asset_qty_cattle,
          asset_qty_otherlivestock,
          asset_qty_sheepgoat,
          memb_total,
          memb_und15,
          memb_15_44,
          hhs_total,
          bio_bio_1,
          bio_bio_12,
          house_owned,
          asset_cartplough, 
          asset_telephone,
          asset_tractor,
          asset_motorbike,
          asset_television,
          asset_radio
        )
```


```{r}
# changing yes to 1 and no to 0
bihs_original = bihs_original%>%mutate(asset_cartplough = ifelse(asset_cartplough=="Yes", "1", "0"),
                                       asset_television = ifelse(asset_television=="Yes", 1, 0),
                                       asset_telephone = ifelse(asset_telephone=="Yes", 1, 0),
                                       asset_tractor = ifelse(asset_tractor=="Yes", 1, 0),
                                       asset_radio = ifelse(asset_radio=="Yes", 1, 0),
                                       asset_motorbike = ifelse(asset_motorbike=="Yes", 1, 0),
                                       asset_cartplough = as.numeric(asset_cartplough)
                                       )

```

```{r}
# create the new variable to use as the response
bihs_original <- bihs_original%>%mutate(tech_asset_count = asset_cartplough + asset_television + 
                                         asset_telephone + asset_tractor + asset_radio + 
                                         asset_motorbike, tech_asset_count = 
                                         as.numeric(tech_asset_count))

```




# Exploratory plots

We selected a fewvariables for the BIHS dataset to see if there might be a relationship between the response `tech_asset_count` and the predictors. The boxplots are shown below.

```{r}
# whether they owned/rented a house
gf_point(data = bihs_original, tech_asset_count ~ fcs )
gf_boxplot(data = bihs_original, tech_asset_count ~ house_owned)
gf_point(data = bihs_original, tech_asset_count ~ asset_qty_sheepgoat)

```



```{r, error=TRUE}
# regression
income_glm <- glm(data = bihs_original, tech_asset_count ~ asset_qty_poultry +
                 asset_qty_cattle + asset_qty_otherlivestock + asset_qty_sheepgoat + 
                 memb_total + memb_und15 + memb_15_44 + hhs_total + bio_bio_1 + 
                 bio_bio_12 + house_owned, family=poisson(link='log'), na.action = 'na.fail')

summary(income_glm)
```







  