---
title: "BIHS Model Fitting"
subtitle: "STAT-245, Calvin University"
author: "Ivanna Rodriguez, Myungha Kim, James Eapen"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: 
  pdf_document:
    fig_height: 2.2
    fig_width: 4
    toc: true
    toc_depth: 2
  html_document:
    fig_height: 2.2
    fig_width: 4
  word_document:
    fig_height: 2.2
    fig_width: 4
---

```{r, setup, include = FALSE}
# load packages that are going to be used
require(tidyverse)   # this loads mosaic, ggformula, etc. too
require(ggformula)
require(mosaic)

# to read excel files
require(readxl)
# for collinearity
require(GGally)
# for IC
require(MuMIn)
# for VIF
require(car)


# Some customization.  You can alter or delete as desired (if you know what you are doing).

theme_set(theme_bw(base_size=12))     # change theme for ggplot2/ggformula

knitr::opts_chunk$set(
  echo = TRUE,      # for homework, always show R code (this is the default)
  tidy = FALSE,     # display code as typed (rather than reformatted)
  size = "small",   # slightly smaller font for code
  message = FALSE, warning = FALSE) # don't print warnings or messages in compiled document. So you MUST check them in RStudio!
```


```{r, include = FALSE}
# reading in the data
bihs <- read_csv('bihs_final.csv')
```


```{r}
more_pred <- lm(fcs ~ factor(year) + memb_total + memb_und15 + memb_15_44 + asset_qty_poultry + mean_annual_temp + annual_precip + hhs_total, data = bihs)
```

